web_download/Areas/Admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webdownload.Areas.Admin.Models;
using webdownload.Models;

namespace webdownload.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class DefaultController : Controller
    {
        private readonly WebDownloadDbContext db = new WebDownloadDbContext();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult sub_category(string friendly_url)
        {
            var cateogry = db.TblCategory.First(r => r.url == friendly_url);
            var sub_categories = db.TblCategory.Where(r => r.ParentID == cateogry.ID);
            return View(sub_categories);
        }

        public IActionResult sub_category_show_list(string friendly_url, int? page)
        {
            try
            {
                const int per_page = 3;
                var cateogry = db.TblCategory.First(r => r.url == friendly_url);
                ViewBag.Category = cateogry;
                var last_page = 0;
                if ((db.TblSoftware.Count() % per_page) > 0)
                {
                    last_page = db.TblSoftware.Count() / per_page + 1;
                }
                else
                {
                    last_page = db.TblSoftware.Count() / per_page;
                }

                if (page.HasValue == false) page = 1;
                var softwares = new List<TblSoftware>();
                if (page > 0)
                {
                    softwares = db.TblSoftware.Where(r => r.categoryID == cateogry.ID).Skip((page.Value - 1) * per_page).Take(per_page).ToList();
                }
                var parent = db.TblCategory.Single(r => r.ID == cateogry.ParentID);
                ViewBag.Parent = parent;
                cateogry.ParentID = parent.ID;
                var model = new subcategorylist_viewmodel()
                {
                    CategoryID = cateogry.ID,
                    page = page.Value,
                    page_count = last_page,
                    softwares = softwares.ToList()
                };
                return View(model);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }

        }

        [HttpPost]
        public JsonResult delete_softwares(string[] checkeds)
        {
            try
            {
                foreach (var id in checkeds)
                {
                    var val = int.Parse(id);
                    var item = db.TblSoftware.First(r => r.ID == val);
                    db.TblSoftware.Remove(item);
                    db.SaveChanges();
                }
                return Json(new
                {
                    message = "ok"
                });
            }
            catch (Exception e)
            {
                return Json(new
                {
                    message = e.InnerException.Message
                });
            }

        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public JsonResult AddNewSoftware_Proc(TblSoftware model)
        {
            try
            {
                int? related_downloadID = null;
                model.DateAdd = DateTime.Now;
                var category_id = int.Parse(Request.Form["categoryID"][0]);
                if (string.IsNullOrWhiteSpace(model.Name))
                {
                    return Json(new
                    {
                        message = "Vui lòng điền tên",
                    });
                }
                model.short_url = FriendlyUrlHelper.GetFriendlyTitle(model.Name);
                model.categoryID = category_id;
                if (Request.Form["related_downloadID"].Count > 0 && !String.IsNullOrWhiteSpace(Request.Form["related_downloadID"][0]))
                {
                    related_downloadID = int.Parse(Request.Form["related_downloadID"][0]);
                    model.related_downloadID = related_downloadID.Value;
                }
                var _new = db.TblSoftware.Add(new TblSoftware()
                {
                    icon = model.icon,
                    categoryID = model.categoryID,
                    Name = model.Name,
                    lience = model.lience,
                    main_download = model.main_download,
                    operating_systems = model.operating_systems,
                    provider = model.provider,
                    rating = model.rating,
                    related_downloadID = model.related_downloadID,
                    short_url = FriendlyUrlHelper.GetFriendlyTitle(model.Name),
                    Visible = model.Visible,
                    viewed = 0,
                    size = 0,
                    downloaded = 0,
                    DateAdd = DateTime.Now,
                    text = model.text,
                    tags = "",
                    version = model.version
                });
                db.SaveChanges();
                return Json(new
                {
                    message = "Tạo mới thành công! ",
                });
            }
            catch (Exception e)
            {
                return Json(new
                {
                    message = e.Message
                });
            }


        }
        public IActionResult AddNewSoftware(string CategoryId)
        {
            ViewBag.CategoryId = CategoryId;
            return View();
        }

        public IActionResult EditSoftware(int Id)
        {
            var model = db.TblSoftware.Find(Id);
            ViewBag.related_download = db.TblSoftware.Find(model.related_downloadID);
            return View(model);
        }
        public JsonResult EditSoftware_Proc(TblSoftware model)
        {
            try
            {
                var c = db.TblSoftware.Find(model.ID);
                c.icon = model.icon;
                c.main_download = model.main_download;
                c.Name = model.Name;
                if (string.IsNullOrWhiteSpace(c.Name))
                {
                    return Json(new
                    {
                        message = "Vui lòng đặt tên",
                    });
                }
                c.operating_systems = model.operating_systems;
                c.provider = model.provider;
                c.related_downloadID = model.related_downloadID;
                c.text = model.text;
                c.version = model.version;
                c.Visible = model.Visible;
                c.size = model.size;
                c.lience = model.lience;
                db.SaveChanges();
                return Json(new
                {
                    message = "Cập nhật thành công",
                });

            }
            catch (Exception e)
            {
                return Json(new
                {
                    message = e.Message,
                });
                throw;
            }

        }
        [HttpGet]
        public JsonResult Autocomplete(string query)
        {
            var data = db.TblSoftware.Where(r => r.Name.Contains(query)).Select(r => new
            {
                data = r.ID,
                value = r.Name
            });
            return Json(new { query = query, suggestions = data });
        }
    }
}

web_download/Areas/Admin/Controllers/FileManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace webdownload.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class FileManagerController : Controller
    {
        string Encode(string text)
        {
            // Create a SHA256   
            using (SHA256 sha256Hash = SHA256.Create())
            {
                // ComputeHash - returns byte array  
                byte[] bytes = sha256Hash.ComputeHash(Encoding.UTF8.GetBytes(text));

                // Convert byte array to a string   
                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }
                return builder.ToString();
            }

        }

        [HttpPost]
        public async Task<JsonResult> Upload_From_ClipboardAsync(string url)
        {
            try
            {
                string rootContentDir = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
                string image_dir = rootContentDir + "/wwwroot/images";
                WebClient wc = new WebClient();
                var data = wc.DownloadData(url);
                var fileName = Encode(url);
                if (!System.IO.Directory.Exists(image_dir))
                {
                    System.IO.Directory.CreateDirectory(image_dir);
                }
                await System.IO.File.WriteAllBytesAsync(image_dir + "/" + fileName + ".jpg", data);
                return Json(new
                {
                    message = "ok",
                    fullpath = Url.Content("/images/" + fileName + ".jpg")
                });
            }
            catch (Exception)
            {

                return Json(new
                {
                    message = "error",
                });
            }

        }
        [HttpPost]
        public async Task<JsonResult> UploadFile(IFormFile file)
        {
            string rootContentDir = AppDomain.CurrentDomain.GetData("DataDirectory").ToString();
            string image_dir = rootContentDir + "/wwwroot/images";

            if (file == null || file.Length == 0)
                return new JsonResult("file not selected");

            var path = Path.Combine(image_dir,file.FileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            return Json(new
            {
                message = "ok",
                fullpath = Url.Content("/images/" + file.FileName)
            });
        }
    }
}

web_download/Areas/Admin/Views/Default/AddNewSoftware.cshtml
<form enctype="multipart/form-data" asp-action="Upload" asp-controller="FileManager" method="post" id="file_upload_form">
    <input type="file" style="visibility:hidden; display:none" id="FileUpload" />
</form>

@using (Html.BeginForm("AddNewSoftware_Proc", "Default", method: FormMethod.Post, htmlAttributes: new { id = "AddNewSoftware_Proc_form" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="card col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card-header">
                <h3>Tạo mới</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-12 col-lg-2">
                        <a href="#"><img src="~/assets/images/eco-product-img-1.png" id="icon" style="width : 100% ; height : 100%" data-toggle="modal" data-target="#myModal" /></a>
                        <input type="hidden" name="icon" value="" />
                        <!-- The Modal -->
                        <div class="modal" id="myModal">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Tuỳ chọn ảnh icon</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        <button type="button" class="btn btn-block" data-toggle="tooltip" data-placement="top" title="Vui lòng copy đường dẫn ảnh vào clipboard rồi ấn vào đây" id="from_clipboard">Copy ảnh từ Url</button>
                                        <button type="button" class="btn btn-block" onclick="$('#FileUpload').click()">Upload ảnh</button>
                                        <button type="button" class="btn btn-block">Chọn ảnh trong thư viện</button>
                                        <button type="button" class="btn btn-block" id="set_default_image">
                                            Ảnh mặc định
                                        </button>

                                    </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary">Xác nhận</button>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-md-12 col-lg-5">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên phần mềm </label>
                            <input type="text" name="Name" class="form-control" placeholder="Tên phần mềm">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Hệ điều hành</label>
                            <input type="text" name="operating_systems" class="form-control" placeholder="Hệ điều hành" />
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-md-12 col-lg-5">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Phiên bản </label>
                            <input type="text" name="version" class="form-control" placeholder="Phiên bản">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nhà cung cấp</label>
                            <input type="text" name="provider" class="form-control" placeholder="Nhà cung cấp">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-12 col-lg-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Friendly Url</label>
                            <input type="text" name="friendly_url" class="form-control" readonly>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Url download</label>
                            <textarea name="main_download" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-12 col-lg-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Phần mềm liên quan </label>
                            <input type="text" id="related_downloadID" class="form-control" placeholder="Gõ tên phần mềm liên quan">
                            <input type="hidden" name="related_downloadID" />

                            <input type="hidden" name="categoryID" value="@ViewBag.CategoryId" />

                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-md-12 col-lg-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Trạng thái hiển thị</label>
                            <div class="checkbox">
                                <label><input type="checkbox" value="1" name="Visible"> Hiện lên web </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-12 col-lg-12">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Giới thiệu phần mềm</label>
                            <div id="editor"></div>
                            <input type="hidden" name="text" id="text" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 col-xs-12 col-md-8 col-lg-8 col-xl-8"></div>
                    <div class="col-12 col-xs-12 col-md-4 col-lg-4 col-xl-4">
                        <button type="button" class="col-md-5 btn btn-success mt-1" id="btnSave">Lưu</button>
                        <button type="button" class="col-md-5 btn btn-default mt-1" onclick="javascript: GoBackWithRefresh() ">Huỷ bỏ</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<style>
    #overlay {
        position: fixed; /* Sit on top of the page content */
        display: none; /* Hidden by default */
        width: 100%; /* Full width (cover the whole page) */
        height: 100%; /* Full height (cover the whole page) */
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0,0,0,0.5); /* Black background with opacity */
        z-index: 1000; /* Specify a stack order in case you're using a different order for other elements */
        cursor: pointer; /* Add a pointer on hover */
    }
</style>
<div id="overlay" onclick="overlay_off()">Đang cập nhật vui lòng chờ đợi</div>
<script>
    function GoBackWithRefresh() {
        if ('referrer' in document) {
            window.location = document.referrer;
            /* OR */
            //location.replace(document.referrer);
        } else {
            window.history.back();
        }
    }

    function overlay_on() {
        document.getElementById("overlay").style.display = "block";
    }

    function overlay_off() {
        document.getElementById("overlay").style.display = "none";
    }
</script>

@section script{
    <script>

        $( "#set_default_image" ).click(function() {
            $("#icon").attr('src', '/assets/images/eco-product-img-1.png');
        });

        $("#btnSave").click(function () {
            $('#text').val(editor.getData());
            var formData = $('#AddNewSoftware_Proc_form').serialize();
            $.ajax({
                url: '@Url.Action("AddNewSoftware_Proc","Default")',
                type: 'POST',
                data: formData,
                dataType: 'json',
                success: function (response) {
                    console.log(response);
                }
            });
        });

        $('#icon').on('load', function () {
            document.getElementsByName('icon')[0].value = $('#icon').attr('src');
        });

        $('#FileUpload').change(function () {
            var fileInput = $('#FileUpload')[0];
            var file = fileInput.files[0];
            var formData = new FormData();
            formData.append('file', file);
            console.log(formData);
            overlay_on();
            $.ajax({
                url: '@Url.Action("UploadFile","FileManager")',
                type: 'POST',
                data: formData,
                async: true,
                cache: false,
                contentType: false,
                enctype: 'multipart/form-data',
                processData: false,
                success: function (response) {
                    console.log('path: ' + response.fullpath);
                    $('#icon').attr('src', response.fullpath);
                    $('#myModal').modal("toggle");
                    overlay_off();
                }
            });
        });

        document.querySelector('#from_clipboard').addEventListener('click', async event => {
          if (!navigator.clipboard) {
            // Clipboard API not available
              alert("Trình duyệt không hỗ trợ clipboard!");
            return
          }
          try {
            const text = await navigator.clipboard.readText()
            overlay_on();
            $.ajax({
                url: '@Url.Action("Upload_From_ClipboardAsync","FileManager")',
                type: 'POST',
                dataType: 'json',
                data: {
                    url: text
                }
            }).done(function (ketqua) {
                if (ketqua.message === 'ok') {
                    console.log('path: ' + ketqua.fullpath);
                    $('#icon').attr('src', ketqua.fullpath);
                    $('#myModal').modal("toggle");
                    overlay_off();
                }


            });
          } catch (err) {
            console.error('Failed to copy!', err)
          }
        })
        $('#related_downloadID').autocomplete({
            serviceUrl: '@Url.Action("autocomplete","default")',
            onSelect: function (suggestion) {
                $('#related_downloadID').val(suggestion.value);
                document.getElementsByName('related_downloadID')[0].value = suggestion.data;
                console.log('You selected: ' + suggestion.value + ', ' + suggestion.data);
            }
        });

        ClassicEditor
            .create(document.querySelector('#editor'), {
                // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(err => {
                console.error(err.stack);
            });
    </script>
}

web_download/Areas/Admin/Views/Default/Index.cshtml
@{
    ViewData["Title"] = "Trang chủ";
}

<h2>Nội dung trang chủ</h2>

web_download/Areas/Admin/Views/Default/sub_category.cshtml
@model IQueryable<TblCategory>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12 rgba-green-strong">
            <div class="card">
                <div class="card-body">
                    <h5 class="text-muted">@item.name</h5>
                    <div class="metric-value d-inline-block">
                        <h1 class="mb-1">
                            <a href="@Url.Action("sub_category_show_list","default", new {friendly_url = item.url})">
                                <img src="@Url.Content(@item.icon)" style="width : 5em; height :5em;"   />
                            </a>
                        </h1>
                    </div>
                    <div class="metric-label d-inline-block float-right text-success font-weight-bold">
                        <div class="input-group-append be-addon">
                           
                        </div>
                    </div>
                </div>

            </div>
        </div>

    }

</div>

web_download/Areas/Admin/Views/Default/sub_category_show_list.cshtml
@using webdownload.Areas.Admin.Models
@model subcategorylist_viewmodel
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">@ViewBag.Parent.name</a></li>
                        <li class="breadcrumb-item">
                            <a href="#" class="breadcrumb-link">
                                <b>@ViewBag.Category.name</b>
                            </a>
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">
                                <input type="checkbox" id="checkall" onclick="$('input:checkbox').prop('checked', $('#checkall').is(':checked'))" />
                            </th>
                            <th scope="col">Icon</th>
                            <th scope="col">Tên</th>
                            <th scope="col">Bản quyền</th>
                            <th scope="col">Dung lượng</th>
                        </tr>
                    </thead>
                    <tbody id="checkboxes">
                        @foreach (var software in Model.softwares)
                        {
                            <tr>
                                <th scope="row">
                                    <input type="checkbox" class="messageCheckbox" name="sport" value="@software.ID" />
                                </th>
                                <td>
                                    <a href="@Url.Action("EditSoftware","Default", new { Id = software.ID })">
                                        <img src="@Url.Content(software.icon)" style="width : 50px; height : 50px;" />
                                    </a>

                                </td>
                                <td>
                                    <a href="@Url.Action("EditSoftware","Default", new { Id = software.ID })">
                                        @software.Name
                                    </a>
                                </td>
                                @if (software.lience == 0)
                                {
                                    <td>Miễn phí</td>
                                }
                                else
                                {
                                    <td>Bản quyền</td>
                                }
                                <td>@(software.size / 1024) MB </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12"></div>
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 ">
        <div class="btn btn-outline-danger   float-right" onclick="delete_selected()" style="width : 110px;">
            <i class="fa fa-trash" aria-hidden="true"></i>
            Xoá
        </div>
        <a href="@Url.Action("AddNewSoftWare","Default",new { CategoryId = Model.CategoryID})" style="text-decoration : none">
            <div class="btn btn-outline-success float-right mr-1" style="width : 110px;">
                <i class="fa fa-plus" aria-hidden="true"></i>
                Thêm mới
            </div>
        </a>
    </div>
</div>




@section script{
    <script>
        function delete_selected(evt) {
            var items = [];
            $.each($("input[name='sport']:checked"), function () {
                items.push($(this).val());
            });
            console.log(items);
            if (items.length == 0) {
                alert("Bạn hãy tick vào các ô để chọn mục cần xoá!");
                return;
            }
            vex.dialog.confirm({
                message: `Bạn thật sự muốn xoá ${items.length} mục đã chọn không?`,
                callback: function (value) {
                    if (value) {

                        $.ajax({
                            url: '@Url.Action("delete_softwares","default")',
                            type: 'POST',
                            dataType: 'json',
                            data: {
                                checkeds: items
                            }
                        }).done(function (response) {
                            if (response.message === 'ok')
                                location.reload();
                            else
                                vex.dialog.alert({ className: 'vex-theme-os example', message: response.message });
                        });
                        console.log('Successfully destroyed the planet.')
                    } else {
                        console.log('Chicken.')
                    }
                }
            })



        }
    </script>
}