web_download/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webdownload.Areas.Admin.Models;
using webdownload.Models;

namespace webdownload.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private webdownload.Models.WebDownloadDbContext db = new webdownload.Models.WebDownloadDbContext();
        
        public IActionResult Index()
        {
            var model = new List<CategoryIndexViewmodel>();
            foreach (var item in db.TblCategory.ToList())
            {
                var _new = new CategoryIndexViewmodel()
                {
                    Icon = item.icon,
                    Id = item.ID,
                    Name = item.name,
                    Order = item.order,
                    Url = item.url,
                };
                if (item.ParentID.HasValue)
                {
                    _new.ParentCategory = db.TblCategory.Find(item.ParentID);
                }
                model.Add(_new);
            }
            return View(model.ToList());
        }
        public IActionResult Delete(int ID)
        {
            var item = db.TblCategory.Find(ID);
            db.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int ID)
        {
            var cat = db.TblCategory.Find(ID);
            var model = new CategoryIndexViewmodel()
            {
                Icon = cat.icon,
                Id = cat.ID,
                Name = cat.name,
                Order = cat.order,
                Url = cat.url,
                text = cat.text
            };
            if (cat.ParentID.HasValue)
            {
                model.ParentCategory = db.TblCategory.Find(cat.ParentID);
            }
            model.TopCategories = db.TblCategory.Where(r => r.ParentID.HasValue == false).ToList();

            return View(model);
        }
        public IActionResult Add()
        {
            var model = new CategoryIndexViewmodel()
            {
                TopCategories = db.TblCategory.Where(r => r.ParentID.HasValue == false).ToList()
            };
            return View(model);
        }
        public IActionResult Add_Proc(TblCategory model)
        {
            if(model.ParentID == -1)
            {
                model.ParentID = null;
            }
            db.TblCategory.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit_Proc(TblCategory model)
        {
            if (model.ParentID == -1)
            {
                model.ParentID = null;
            }

            db.Entry(model).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

web_download/Areas/Admin/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using webdownload.Areas.Admin.Models;
using webdownload.Models;

namespace webdownload.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class SearchController : Controller
    {
        private readonly WebDownloadDbContext db = new WebDownloadDbContext();
        public IActionResult Index(string keyword)
        {
            var model = new IndexSearchViewmodel();
            var list = db.TblSoftware.Where(r => r.Name.ToLower().Contains(keyword.ToLower())).Take(10);
            model.Keyword = keyword;
            model.Softwares = new List<TblSoftware>();
            model.Softwares = list.ToList();

            model.found = list.Count();
            model.total = db.TblSoftware.Count();
            return View(model);
        }
    }
}

web_download/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    var db = new WebDownloadDbContext();
    var top_categories = db.TblCategory
        .Where(r => r.ParentID == null)
        .OrderBy(r => r.order)
        .ToList();

}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="/assets/libs/css/style.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/fontawesome/css/all.css">
    <link rel="stylesheet" href="~/assets/vendor/ckeditor5-build-classic/sample/css/sample.css" />
    <link rel="stylesheet" href="/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css">
    <script src="~/assets/vendor/vex/dist/js/vex.combined.min.js"></script>
    <script>vex.defaultOptions.className = 'vex-theme-os'</script>

    <link rel="stylesheet" href="~/assets/vendor/vex/dist/css/vex.css" />
    <link rel="stylesheet" href="~/assets/vendor/vex/dist/css/vex-theme-os.css" />
    <title>Download - Download miễn phí </title>
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                <a class="navbar-brand" href="/">Download</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top">
                        <li class="nav-item">
                            @using (Html.BeginForm("Index", "Search",method : FormMethod.Get))
                            {
                                <div id="custom-search" class="top-search-bar">
                                    <input class="form-control" type="text" placeholder="Tìm phần mềm theo tên.." name="keyword" id="keyword">
                                </div>
                            }
                        </li>
                        
                        
                        <li class="nav-item dropdown nav-user">
                            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/assets/images/avatar-0.png" alt="" class="user-avatar-md rounded-circle"></a>
                            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                                <div class="nav-user-info">
                                    <h5 class="mb-0 text-white nav-user-name">@User.Identity.Name</h5>
                                    <span class="status"></span><span class="ml-2">Đang online</span>
                                </div>
                                <a class="dropdown-item" href="@Url.Action(action : "signout", controller : "account")"><i class="fas fa-power-off mr-2"></i>Đăng xuất</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        <div class="nav-left-sidebar sidebar-dark">
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-divider">
                                Quản trị
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-6" aria-controls="submenu-6"><i class="fas fa-fw fa-file"></i> Phần mềm </a>
                                <div id="submenu-6" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            @foreach (var category in top_categories)
                                            {
                                                <a class="nav-link" href="@Url.Action("sub_category","default", new { friendly_url = category.url })">@category.name</a>
                                            }
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-7" aria-controls="submenu-7"><i class="fas fa-fw fa-file"></i> Admin </a>
                                <div id="submenu-7" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                               <a class="nav-link" href="@Url.Action("Index","Category")">Quản lý chuyên mục</a>
                                               <a class="nav-link" href="#">Cập nhật User</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end left sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- wrapper  -->
        <!-- ============================================================== -->
        <div class="dashboard-wrapper">
            <div class="dashboard-ecommerce">
                <div class="container-fluid dashboard-content ">
                    @RenderBody()
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <div class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            Copyright © 2018 Concept. All rights reserved. Dashboard by <a href="https:/colorlib.com/wp/">Colorlib</a>.
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                            <div class="text-md-right footer-links d-none d-sm-block">
                                <a href="javascript: void(0);">About</a>
                                <a href="javascript: void(0);">Support</a>
                                <a href="javascript: void(0);">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- end wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper  -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <script src="~/assets/vendor/jQueryautocomplete/dist/jquery.autocomplete.js"></script>

    <!-- bootstap bundle js -->
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <!-- main js -->
    <script src="/assets/libs/js/main-js.js"></script>
    <script src="~/assets/vendor/ckeditor5-build-classic/ckeditor.js"></script>
    <script>
        // Get the input field
        var input = document.getElementById("keyword");
        // Execute a function when the user releases a key on the keyboard
        input.addEventListener("keyup", function(event) {
            // Number 13 is the "Enter" key on the keyboard
            if (event.keyCode === 13) {
            // Cancel the default action, if needed
                event.preventDefault();
                document.forms.search_form.submit();
            }
        });
    </script>
    @RenderSection("script", required: false)
</body>

</html>